spring.application.name=web
api.base-url=${API_BASE_URL:https://openapi.gg.go.kr/GGCULTUREVENTSTUS}
api.key=${API_KEY}
api.page-index=${API_PAGE_INDEX:1}
api.page-size=${API_PAGE_SIZE:200}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

server.servlet.session.timeout=30m
server.error.whitelabel.enabled=false

logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.tomcat.relaxed-path-chars=[,],{,},^,|,`
server.tomcat.relaxed-query-chars=[,],{,},^,|,`


spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


spring.web.resources.static-locations=classpath:/static/, classpath:/public/, classpath:/resources/\
  , classpath:/META-INF/resources/

server.port=${PORT:8080}

